# SERVER
server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#Spring 
spring:
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  # OAuth  
  security:
    oauth2:
      client:
        registration:
          # Google
          google:
            client-id: deleted apps
            client-secret: deleted apps
            scope:
            - email
            - profile
            #redirect-uri: http://localhost:8888/login/oauth2/code/google
          # Facebook
          facebook:
            client-id: deleted apps
            client-secret: deleted apps
            scope:
            - email
            - public_profile
            #redirect-uri: http://localhost:8888/login/oauth2/code/facebook
          # Naver
          naver: # ERROR MESSAGE: Provider ID must be specified for client registration 'naver'
            client-id: deleted apps
            client-secret: deleted apps
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code #방식이 서로 다름.
            redirect-uri: http://localhost:8888/login/oauth2/code/naver #고정아님.
            
        provider:
          # 네이버는 OAuth provider가 등록 되어있지 않음. >> 서버 기동 시 ERROR
          naver: # 네이버 개발자 문서 로그인 3.4.*
            # /oauth2/authorization/naver 은 아래 URL로 요청.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 JSON으로 받는데 response라는 키값으로 네이버가 리턴해줌.
              
## 머스테치는 아래 설정이 기본. or WebMvcConfig Resolver
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache
  # JPA
  jpa:
    hibernate:
      ddl-auto: update #create는 데이터베이스를 비움. update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# TEST SUCCESS


